export const data = [
    {
      id: 0,
      category: "announcement",
      time: "33 minutes ago",
      title: "Do you want to build a great team? Contact Google",
      image: "http://sites.psu.edu/leadership/wp-content/uploads/sites/8069/2015/03/google_AU_team-730285.png",
      author: "Mark Zuckerberg",
      modalTitle: "This is a standard 1500s text, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularized in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker, including versions of Lorem Ipsum.",
    },
    {
      id: 1,
      category: "recruitment",
      time: "17 minutes ago",
      title: "Meeting at Google's Headquarters in 2 hours to Discuss Projects",
      image: "https://g.foolcdn.com/editorial/images/446553/meeting_gettyimages-603992138.jpg",
      author: "Mark Zuckerberg",
      modalTitle: "This is a standard 1500s text, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularized in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker, including versions of Lorem Ipsum.",
    },
    {
      id: 2,
      category: "training",
      time: "25 minutes ago",
      title: "Ensure Mandatory Confirmation Code for Training",
      image: "https://learn.microsoft.com/en-us/compliance/media/assurance-sdl-process-diagram.png",
      modalTitle: "This is a standard 1500s text, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularized in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker, including versions of Lorem Ipsum.",
      author: "Mark Zuckerberg",
    },
    {
      id: 3,
      category: "announcement",
      time: "33 minutes ago",
      title: "Want to Create a Large Group? Connect with Google",
      image: "http://sites.psu.edu/leadership/wp-content/uploads/sites/8069/2015/03/google_AU_team-730285.png",
      author: "Mark Zuckerberg",
      modalTitle: "This is a standard 1500s text, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularized in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker, including versions of Lorem Ipsum.",
    },
    {
      id: 4,
      category: "recruitment",
      time: "17 minutes ago",
      title: "Meeting at Google's Headquarters in 2 hours to Discuss Projects",
      image: "https://g.foolcdn.com/editorial/images/446553/meeting_gettyimages-603992138.jpg",
      author: "Mark Zuckerberg",
      modalTitle: "This is a standard 1500s text, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularized in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker, including versions of Lorem Ipsum.",
    },
    {
      id: 5,
      category: "training",
      time: "25 minutes ago",
      title: "Make Sure to Confirm Mandatory Code for Training",
      image:"https://www.aihr.com/wp-content/uploads/training-needs-analysis-cover.png",
      author: "Mark Zuckerberg",
      modalTitle: "This is a standard 1500s text, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularized in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker, including versions of Lorem Ipsum.",
    },
  ];
  